# Generated by Django 6.0.1 on 2026-02-03 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_character'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='photo',
            new_name='photo2',
        ),
    ]
