# Generated by Django 6.0.2 on 2026-02-23 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='update_time',
            new_name='updated_time',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
